Fix several bugs, prepare PyTorch hub support Bugs fixed:  * `AttributeError: spacy.pipeline.DependencyParser object has no attribute 'labels'` -> Allow spacy versions greater 2.*  * `ModuleNotFoundError: No module named 'models.singletarget.stancedetectionpaper'` -> Local import in method where it's required  * `ModuleNotFoundError: No module named 'models.singletarget.knowledgesourceshosseiniatdbert'` -> Local import in method where it's required  * `from transformers.modeling_bert import BertPooler, BertSelfAttention` -> `from transformers.models.bert.modeling_bert import BertPooler, BertSelfAttention`